print("welcome back")
print("how is the day?")
a = input(("enter your day:"))
print("glad to hear your day is," +  a)
print("how old are you?")
b = input(("My age is:"))
print("You will be " + str(b + 1) + " in a year.")
